### ISSUE TITLE
2 Errors fix

### ISSUE THREAD

**Issue by ze4rch1tect** [akajhon/MailHeaderDetective#2]
Hi, thank you for the tool. However, I encountered and resolved two issues:

1. After reviewing Maltiverse's API documentation, I found that the values for 'classification' are different from those written in url_checker.py and ip_checker.py. Here are the correct values: [malicious, suspicious, neutral, whitelisted].

2. In url_checker.py, there is no 'message' key present in the response. Therefore, attempting to access 'message' as in the original code will raise an error.

The corrected function is as follows:

```
def query_maltiverse(url, maltiverse_api):
    try:
        maltiverse_response = maltiverse_api.url_get(url)
        maltiverse_classification = maltiverse_response['classification']
        if maltiverse_classification == 'malicious':
            return "Malicious"
        elif maltiverse_classification == 'suspicious':
            return "Suspicious"
        elif maltiverse_classification == 'neutral':
            return "Neutral"
        else:
            return 'Safe'
    except Exception as e:
        print(f"[!] Error in query_maltiverse: {e}")
        return "Error"
```

After fixing these 2 issues, it works perfectly !

**Comment by akajhon** [comment]
Hello, @ze4rch1tect !

Thank you for reviewing the code and identifying these discrepancies. I really appreciate your efforts in correcting the classification values and response handling. The corrected function looks great and has already been merged to the main branch!

I hope the tool is serving you well. Please feel free to continue providing feedback, suggesting changes, or discussing further enhancements!
